name: "Cross-Platform Build: AriaDownloader (Win + Mac + Linux)"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Confirm Python and pip
      run: |
        echo "PATH: $PATH"
        which python
        python --version
        pip list

    - name: Ensure assets directory exists
      run: mkdir -p assets
      shell: bash

    - name: Clear existing assets
      run: rm -rf assets/*
      shell: bash

    - name: Download and prepare assets (Linux)
      if: runner.os == 'Linux'
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o assets/yt-dlp
        sudo apt-get update
        sudo apt-get install -y aria2
        cp /usr/bin/aria2c assets/aria2c
        chmod +x assets/yt-dlp
        chmod +x assets/aria2c

    - name: Download and prepare assets (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe" -OutFile "assets/yt-dlp.exe"
        Copy-Item "assets/yt-dlp.exe" "assets/yt-dlp"
        Invoke-WebRequest -Uri "https://github.com/aria2/aria2/releases/latest/download/aria2-1.37.0-win-64bit-build1.zip" -OutFile "aria2.zip"
        Expand-Archive -Path aria2.zip -DestinationPath .
        Move-Item -Path "aria2-1.37.0-win-64bit-build1/aria2c.exe" -Destination "assets/aria2c.exe"
        Copy-Item "assets/aria2c.exe" "assets/aria2c"
        Remove-Item aria2.zip
        Remove-Item -Recurse -Force aria2-1.37.0-win-64bit-build1

    - name: Download and prepare assets (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install aria2
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o assets/yt-dlp
        cp $(which aria2c) assets/aria2c
        chmod +x assets/yt-dlp
        chmod +x assets/aria2c

    - name: Build with PyInstaller
      run: python -m PyInstaller build.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AriaDownloader-${{ runner.os }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "AriaDownloader v1.0.${{ github.run_number }}"
          body: |
            🚀 New cross-platform release of AriaDownloader:
            - ✅ Windows
            - ✅ macOS
            - ✅ Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "AriaDownloader"
          files: ./artifacts/**/*

